LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_SRC_FILES := updateprop.c
LOCAL_MODULE := updateprop
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)
LOCAL_FORCE_STATIC_EXECUTABLE := true
LOCAL_MULTILIB := 32

include $(BUILD_EXECUTABLE)

